[2022-08-18 16:32:41,004] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Satellite_Data.load_into_json scheduled__2022-08-17T16:27:27.612326+00:00 [queued]>
[2022-08-18 16:32:41,015] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Satellite_Data.load_into_json scheduled__2022-08-17T16:27:27.612326+00:00 [queued]>
[2022-08-18 16:32:41,015] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-18 16:32:41,015] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-08-18 16:32:41,015] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-18 16:32:41,040] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): load_into_json> on 2022-08-17 16:27:27.612326+00:00
[2022-08-18 16:32:41,046] {standard_task_runner.py:52} INFO - Started process 1299 to run task
[2022-08-18 16:32:41,049] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Satellite_Data', 'load_into_json', 'scheduled__2022-08-17T16:27:27.612326+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/data_loader.py', '--cfg-path', '/tmp/tmpuh6fxygx', '--error-file', '/tmp/tmpf1z1pwdr']
[2022-08-18 16:32:41,050] {standard_task_runner.py:80} INFO - Job 70: Subtask load_into_json
[2022-08-18 16:32:41,141] {task_command.py:371} INFO - Running <TaskInstance: Satellite_Data.load_into_json scheduled__2022-08-17T16:27:27.612326+00:00 [running]> on host b4db7d4790c9
[2022-08-18 16:32:41,284] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Satellite_Data
AIRFLOW_CTX_TASK_ID=load_into_json
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T16:27:27.612326+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-17T16:27:27.612326+00:00
[2022-08-18 16:32:41,285] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-18 16:32:41,285] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/satelliteTrack.py']
[2022-08-18 16:32:41,301] {subprocess.py:85} INFO - Output:
[2022-08-18 16:32:42,960] {subprocess.py:92} INFO - <Response [500]>
[2022-08-18 16:32:42,961] {subprocess.py:92} INFO - Traceback (most recent call last):
[2022-08-18 16:32:42,963] {subprocess.py:92} INFO -   File "/opt/***/dags/satelliteTrack.py", line 108, in <module>
[2022-08-18 16:32:42,964] {subprocess.py:92} INFO -     load_satellite_data()
[2022-08-18 16:32:42,964] {subprocess.py:92} INFO -   File "/opt/***/dags/satelliteTrack.py", line 88, in load_satellite_data
[2022-08-18 16:32:42,965] {subprocess.py:92} INFO -     data = api_call()
[2022-08-18 16:32:42,965] {subprocess.py:92} INFO -   File "/opt/***/dags/satelliteTrack.py", line 70, in api_call
[2022-08-18 16:32:42,965] {subprocess.py:92} INFO -     raise MyError(resp, "GET fail on request for Starlink satellites")
[2022-08-18 16:32:42,965] {subprocess.py:92} INFO - __main__.MyError: (<Response [500]>, 'GET fail on request for Starlink satellites')
[2022-08-18 16:32:43,039] {subprocess.py:96} INFO - Command exited with return code 1
[2022-08-18 16:32:43,063] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-08-18 16:32:43,066] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=Satellite_Data, task_id=load_into_json, execution_date=20220817T162727, start_date=20220818T163241, end_date=20220818T163243
[2022-08-18 16:32:43,091] {standard_task_runner.py:97} ERROR - Failed to execute job 70 for task load_into_json (Bash command failed. The command returned a non-zero exit code 1.; 1299)
[2022-08-18 16:32:43,105] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-18 16:32:43,156] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
